name: Run Bot

on:
  push:

jobs:
  bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run bot
        env:
          TOKEN: ${{ secrets.TOKEN }}
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
        run: npm install discord.js && node deploy-commands.js && node index.js
